# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('data_de_nascimento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reconhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(max_length=200)),
                ('data', models.DateField(auto_now_add=True)),
                ('reconhecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconhecedor', to=settings.AUTH_USER_MODEL)),
                ('reconhecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconhecido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='reconhecimento',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconhecimentos.Valor'),
        ),
    ]
